Neural networks
ml-vision-usp/ml-book pull request #23
Opened 2024-06-04 17:29 UTC by Kaiqoliver

Neural Network Chapter

2024-06-07 00:41 UTC, jooag submitted a review, later dismissed
tem uns typos, e precisa tirar os comentarios
de resto ficou muito bom =)

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +Para começar, temos que saber que cada neurônio recebe como entrada uma soma ponderada pelos pesos e viéses sobre as saídas da camada anterior. O resultado dessa soma é então aplicada em uma **função
>  ... para introduzir não=linearidade nas saídas...
há um typo

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +Para começar, temos que saber que cada neurônio recebe como entrada uma soma ponderada pelos pesos e viéses sobre as saídas da camada anterior. O resultado dessa soma é então aplicada em uma **função
```suggestion
Para começar, temos que saber que cada neurônio recebe como entrada uma soma ponderada pelos pesos e viéses sobre as saídas da camada anterior. O resultado dessa soma é então aplicada em uma **função de ativação**, com a saída dessa função sendo também a saída do neurônio. As funções de ativação são utilizadas nos neurônios para introduzir não-linearidade nas saídas das redes neurais. Algumas das funções comumente utilizadas são a sigmoide, a ReLU, e a tangente hiperbólica. A escolha da função de ativação pode afetar a performance do modelo.
```

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +O algorítmo backpropagation é uma forma eficiente de se computar o gradiente $$\nabla\bold{\mathcal{L}(w)}$$ de uma função de perda que uma rede neural possui. Com frequência utilizamos o erro quadrá
Tem problema com o nabla, compila o latex em https://quicklatex.com/ e coloca como imagem por enquanto T-T

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +    \frac{\partial e}{\partial w_{ij}^{(l)}} = \bold{x}_{i}^{(l-1)} . \bold{\delta}_{j}^{(l)}
Para ficar o ponto centralizado, dá pra usar o \cdot =D

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +    \frac{\partial e}{\partial w_{ij}^{(l)}} = \bold{x}_{i}^{(l-1)} . \bold{\delta}_{j}^{(l)}
```suggestion
    \frac{\partial e}{\partial w_{ij}^{(l)}} = \bold{x}_{i}^{(l-1)} \cdot \bold{\delta}_{j}^{(l)}
```

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +    \frac{\partial e}{\partial \bold{s}^{(l)}} = \frac{\partial e}{\partial \bold{x}^{(l)}} . \frac{\partial \bold{x}^{(l)}}{\partial \bold{s}^{(l)}}
```suggestion
    \frac{\partial e}{\partial \bold{s}^{(l)}} = \frac{\partial e}{\partial \bold{x}^{(l)}} \cdot \frac{\partial \bold{x}^{(l)}}{\partial \bold{s}^{(l)}}
```

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +    \bold{\delta}_{j}^{(l)} = \frac{\partial e}{\partial\bold{s}_{j}^{(l)}} = \frac{\partial e}{\partial \bold{x}_{j}^{(l)}} . \frac{\partial \bold{x}_{j}^{(l)}}{\partial\bold{s}_{j}^{(l)}}
```suggestion
    \bold{\delta}_{j}^{(l)} = \frac{\partial e}{\partial\bold{s}_{j}^{(l)}} = \frac{\partial e}{\partial \bold{x}_{j}^{(l)}} \cdot \frac{\partial \bold{x}_{j}^{(l)}}{\partial\bold{s}_{j}^{(l)}}
```

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +**Me digam o que acham, por enquanto seguirei assumindo que o Mostafa estava correto**
Achei um pouco esquisito também, mas acho que está assim porque a função pode depender dos outros elementos do vetor. Um exemplo é a softmax. Concorda, @Fernando-crz?

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +**Essas derivadas com vetores aqui tão certas?**
Me parece que sim

2024-06-07 00:41 UTC, jooag commented on redes-neurais/redes-neurais.md
> +
Vi que você adicionou varias imagens no repositorio. Vc planeja coloca-las aqui? Acho que redes-neurais/imagens/exemplo_rede_neural.png e ficariam top c=

2024-06-12 13:41 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +Para começar, temos que saber que cada neurônio recebe como entrada uma soma ponderada pelos pesos e viéses sobre as saídas da camada anterior. O resultado dessa soma é então aplicada em uma **função
- Feito

2024-06-12 13:42 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +Para começar, temos que saber que cada neurônio recebe como entrada uma soma ponderada pelos pesos e viéses sobre as saídas da camada anterior. O resultado dessa soma é então aplicada em uma **função
- Feito

2024-06-12 13:47 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +O algorítmo backpropagation é uma forma eficiente de se computar o gradiente $$\nabla\bold{\mathcal{L}(w)}$$ de uma função de perda que uma rede neural possui. Com frequência utilizamos o erro quadrá
- Feito

2024-06-12 13:49 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +    \frac{\partial e}{\partial w_{ij}^{(l)}} = \bold{x}_{i}^{(l-1)} . \bold{\delta}_{j}^{(l)}
- Feito

2024-06-12 13:49 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +    \frac{\partial e}{\partial w_{ij}^{(l)}} = \bold{x}_{i}^{(l-1)} . \bold{\delta}_{j}^{(l)}
- Feito

2024-06-12 13:50 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +    \frac{\partial e}{\partial \bold{s}^{(l)}} = \frac{\partial e}{\partial \bold{x}^{(l)}} . \frac{\partial \bold{x}^{(l)}}{\partial \bold{s}^{(l)}}
- Feito

2024-06-12 13:50 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +    \bold{\delta}_{j}^{(l)} = \frac{\partial e}{\partial\bold{s}_{j}^{(l)}} = \frac{\partial e}{\partial \bold{x}_{j}^{(l)}} . \frac{\partial \bold{x}_{j}^{(l)}}{\partial\bold{s}_{j}^{(l)}}
- Feito

2024-06-12 13:52 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +**Essas derivadas com vetores aqui tão certas?**
- Feito

Deixei meu comentário comentado

2024-06-12 14:07 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +
- Feito

Não tava aparecendo elas pq eu digitei as barras erradas. Agora elas estão aparecendo

2024-06-13 19:10 UTC, Fernando-crz requested changes
Por favor, dar uma olhada em minhas mudanças pedidas

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +Redes Neurais são um modelo computacional composto por camadas de neurônios artificiais, também conhecidos como unidades de processamento, que são interconectados com o objetivo de aprender tarefas c
O que significa "no tocante a processamento de informação."?

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +Antes de adentrar cada passo do processo de modo mais detalhado, primeiro será apresentado um resumo de todo o processo. Desse modo o leitor terá um panorama geral prévio antes de começar a ver cada
Ao invés de escrever o trecho de forma impessoal:
```

[...] Desse modo o leitor terá um panorama geral prévio antes de começar a ver cada tópico.
```
Acredito que seria mais proveitoso escrevê-lo como:
```suggestion
Antes de adentrar cada passo do processo de modo mais detalhado, primeiro será apresentado um resumo de todo o processo. Desse modo, teremos um panorama geral prévio antes de começar a ver cada tópico.
```

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +As camadas são rotuladas por $$l = 0,1,2, ..., L$$ e, como podemos ver, a camada $$l = 0$$ é a nossa camada de entrada - interessante dizer que, dependendo da fonte, a camada de entrada nem sempre é
```
Neste capítulo utilizaremos este $$\text{índice}^{(l)}$$ para fazer referência ...
```
Melhor deixar um pouco mais claro esse trecho, o uso de "texto" elevado à certo índice deixa as coisas um pouco mais difíceis de entender.

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +Observe que o nó $$j$$ possui um sinal $$s$$ de entrada com uma saída $$x$$, baseado nisso nós criaremos dois vetores: o vetor $$\bold{s}^{(l)}$$ e o vetor $$\bold{x}^{(l)}$$. O primeiro vetor - $$\b
```
O primeiro vetor - $$\bold{s}^{(l)}$$ - será o vetor sinal ....
```
Acho uma boa tirar esses hífens ("-") entre a variável, já que podem ser confundidos como sinal da variável.

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +Observe que o nó $$j$$ possui um sinal $$s$$ de entrada com uma saída $$x$$, baseado nisso nós criaremos dois vetores: o vetor $$\bold{s}^{(l)}$$ e o vetor $$\bold{x}^{(l)}$$. O primeiro vetor - $$\b
```
lembre-se que o nó zero não possui nenhum sinal de entrada
```
Acho que não é uma boa falar que o nó zero não possui nenhum sinal de entrada. Ao invés disso, pode dizer que a entrada do nó zero é dada pelo usuário do modelo.

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +    \frac{\partial\mathcal{L}(\bold{w})}{\partial W^{l}} = \frac{1}{N}\sum_{n=1}^{N}\frac{\partial e_{n}}{\partial W^{(l)}}
faltou um parênteses aqui no W^{l}

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +Estas são as derivadas parciais que desejamos encontrar. Para encontrá-las, a ideia é computar as derivadas parciais da camada $$l$$ utilizando as derivadas parciais encontradas para a partir da cama
acho uma boa colocar "sensibilidade" em negrito aqui

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +    \delta^{(l)} = \frac{\partial e}{\partial \bold{s}^{(l)}} =
Qual a definição de ```e```? ```e_n``` foi definido, entretanto, ```e``` não foi...

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +    \bold{\delta}^{(l)} = \sigma'(\bold{s}^{(l)}) \otimes [W^{(l+1)}\bold{\delta}^{(l+1)}]_{1}^{d^{(l)}}
essa função ```\sigma'``` não foi definida. De onde ela veio?

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +    \frac{\partial \bold{x}_{j}^{(l)}}{\partial \bold{s}_{j}^{(l)}} = \sigma'(\bold{s}_{j}^{(l)}) \Longrightarrow \bold{\delta}_{j}^{(l)} = \frac{\partial e}{\partial \bold{x}_{j}^{(l)}} . \sigma'(\b
Concordo com você!

2024-06-13 19:10 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +Para atualizar os pesos para uma única iteração do gradiente descendente com learning rate fixo, basta fazer $$W^{(l)} \leftarrow W^{(l)} - \eta G^{(l)}$$, for $$l = 1,...,L$$. Existem diversos detal
Typo em "for": ```basta fazer $$W^{(l)} \leftarrow W^{(l)} - \eta G^{(l)}$$, for $$l = 1,...,L$$.```

2024-06-22 18:58 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +Antes de adentrar cada passo do processo de modo mais detalhado, primeiro será apresentado um resumo de todo o processo. Desse modo o leitor terá um panorama geral prévio antes de começar a ver cada
- Feito

2024-06-22 19:02 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +As camadas são rotuladas por $$l = 0,1,2, ..., L$$ e, como podemos ver, a camada $$l = 0$$ é a nossa camada de entrada - interessante dizer que, dependendo da fonte, a camada de entrada nem sempre é
- Sugestão não aceita

2024-06-22 19:08 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +Observe que o nó $$j$$ possui um sinal $$s$$ de entrada com uma saída $$x$$, baseado nisso nós criaremos dois vetores: o vetor $$\bold{s}^{(l)}$$ e o vetor $$\bold{x}^{(l)}$$. O primeiro vetor - $$\b
- Feito

2024-06-22 19:09 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +Observe que o nó $$j$$ possui um sinal $$s$$ de entrada com uma saída $$x$$, baseado nisso nós criaremos dois vetores: o vetor $$\bold{s}^{(l)}$$ e o vetor $$\bold{x}^{(l)}$$. O primeiro vetor - $$\b
- Sugestão não acatada

Releia a definição do nó zero

2024-06-22 19:11 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +Estas são as derivadas parciais que desejamos encontrar. Para encontrá-las, a ideia é computar as derivadas parciais da camada $$l$$ utilizando as derivadas parciais encontradas para a partir da cama
- Feito

2024-06-22 19:15 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +    \delta^{(l)} = \frac{\partial e}{\partial \bold{s}^{(l)}} =
- Feito

2024-06-22 19:19 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +    \bold{\delta}^{(l)} = \sigma'(\bold{s}^{(l)}) \otimes [W^{(l+1)}\bold{\delta}^{(l+1)}]_{1}^{d^{(l)}}
- Feito

2024-06-22 19:20 UTC, Kaiqoliver commented on redes-neurais/redes-neurais.md
> +    \frac{\partial \bold{x}_{j}^{(l)}}{\partial \bold{s}_{j}^{(l)}} = \sigma'(\bold{s}_{j}^{(l)}) \Longrightarrow \bold{\delta}_{j}^{(l)} = \frac{\partial e}{\partial \bold{x}_{j}^{(l)}} . \sigma'(\b
- Alterei

2024-06-27 12:55 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +    \frac{\partial\mathcal{L}(\bold{w})}{\partial W^{l}} = \frac{1}{N}\sum_{n=1}^{N}\frac{\partial e_{n}}{\partial W^{(l)}}
@Kaiqoliver resolver isso aqui

2024-06-27 12:56 UTC, Fernando-crz commented on redes-neurais/redes-neurais.md
> +Observe que o nó $$j$$ possui um sinal $$s$$ de entrada com uma saída $$x$$, baseado nisso nós criaremos dois vetores: o vetor $$\bold{s}^{(l)}$$ e o vetor $$\bold{x}^{(l)}$$. O primeiro vetor - $$\b
de fato, faz todo sentido. LGTM então

2024-06-27 13:07 UTC, Fernando-crz approved these changes

2024-06-27 13:09 UTC, merged